Add AS431 model to simulation for comparison
* Create local library to host TL431 symbol linked to simulation model.
* Use AS431 from Diodes Inc. as simulation model for TL431
* Add some little update/modifs/fix to simulation model since the
  simulator complains about a syntax error :
  ```
      Error on line 24 or its substitute:
      .nodeset r3_n 1
      Error: .nodeset syntax error.
      Error: circuit not parsed.
  ```
  This is documented within the model in case I understand what's wrong
  and find an actual way to fix it instead of the current workaround.